### ISSUE TITLE
productsのジャンル別表示

### ISSUE THREAD

**Issue by keishi-yamamoto** [dwc-pillows/nagano_cake#34]
誰か部分テンプレート部分をお願いします。。。。

**Comment by keishi-yamamoto** [comment]
部分テンプレートの雛形完成確認。
実際にリンク押した際にジャンル別に表示させる必要あり。
・/users/products/cakeのようにジャンル別ページ作る
・どのボタンを押したかでコントローラ内で表示分岐させる（admins/orders#index参考）
この二択が考えられるでしょうか。

**Comment by way-key** [comment]
作成が終わりました。
リンクを押したらジャンルIDをつけて"Search"アクション(user/products内に新規作成)に飛ぶようにし、そこで変数を持たせてindexページにrenderすることで対応しました。
