### ISSUE TITLE
[機能重要度低低]adminからorder.postageを変更できるように

### ISSUE THREAD

**Issue by keishi-yamamoto** [dwc-pillows/nagano_cake#51]
アドミンが変える可能性のあるカラムに対してそれぞれ編集できるようになっているかどうか確認し、不可能な場合編集画面を追加する。
現状だとpostageはデフォルトの値のみを参照していて変更できないようになっているように記憶している。

**Comment by keishi-yamamoto** [comment]
新しく画面作らないといけないしそもそも他に全般で設定する項目もないので後回し

**Comment by way-key** [comment]
実装は行わないことにします。
