### ISSUE TITLE
[Test]管理者ページ_注文と注文商品のステータス変更がリンクする様に

### ISSUE THREAD

**Issue by way-key** [dwc-pillows/nagano_cake#52]
・注文ステータスが【入金確認】になった場合、注文商品の制作ステータスが【制作待ち】となる
・逆に、制作ステータスが全て【制作完了】になった場合、注文ステータスは【発送待ち】となる

・・・ようにコントローラを修正したい

**Comment by keishi-yamamoto** [comment]
入金確認の方もどうにかして変わるようにしないといけないですね。
