### ISSUE TITLE
[Must]発表用

### ISSUE THREAD

**Issue by keishi-yamamoto** [dwc-pillows/nagano_cake#79]
1.メンバー紹介・製作した上での役割分担
2.製作物のアピールポイント（動作デモ）
3.設計フェーズで悩んだこと・工夫したこと
4.チーム開発から学び得たこと

**Comment by keishi-yamamoto** [comment]
1.
山本桂史
担当：ER図、詳細設計、進捗管理・開発進行ルール決め・issue管理、デバイス機能、注文機能
2.
注文未確定の状態を新たに定義したということを伝えたいです。
3.
あるカラムを他のカラムとの関係式によって定義したいときにモデル・コントローラどちらに記述するのが適切か、またそれによってdb内の当該カラムの値がどのように振舞うかについて悩みました。
注文未確定の状態判別においては確定するメソッドにおいてカートアイテムを注文商品にいれるということであるユーザの最新の注文についてその注文商品の存在を確認することで判別するというメソッドを考えた点は工夫した点です。
4.
チーム開発ならではのgithubのレポジトリやコードの記述、さらには作業の進め方についてのルール決めが重要だと言うことを学べました。また他人のコードを見て参考にするということや自分の理解して記述したコードを他人に説明するということの難しさ、重要性も学べました。

**Comment by way-key** [comment]
1.植木達也
担当：アプリケーション詳細設計、カート機能、会員情報編集機能、ジャンル機能、注文履歴機能(管理者側)、顧客一覧機能(管理者側)

2,管理者と顧客が同時ログインできないようにしたこと

3,顧客側のトップ、商品一覧ページのジャンル検索機能です。最初は検索結果を表示するviewページを作ろうかと考えていました。最終的には新規アクションを商品のコントローラに作成し、そこへ遷移することで、該当ジャンルの商品一覧を定義した変数を持たせてindex画面へrenderさせるようにしました。そうすることでindex画面を擬似的に部分テンプレート扱いにしてコードの削減が行えました。

4,スケジュール管理についてです。当初は大まかにコントローラ別に分けて分担分けしていましたが、機能の実装を優先しviewの作成は全ての機能が終了した後になっていました。今回のチーム開発では作業内容の詳細化とチーム内での作業分担の擦り合わせが重要と学びました。

**Comment by keishi-yamamoto** [comment]
（2.校正版）
存在していた問題点
初期のワイヤフレームでは注文確認画面から注文確定ボタンを押さずに他のページに遷移した場合注文が確定されない状況を作り出すことができた。
そもそも、一度確認画面に行ったらお届け先やカート内アイテムの編集を行うことができなかった。
解決方法
まず注文を編集する機能を追加した。
次にユーザモデル内に自身の最新の注文に対して注文商品が存在するかどうか（注文確認画面において確定ボタンが押されたかどうか）を判別するメソッドを書いた。
そして未確定の状況下ではログアウトのリンク先を確認画面にするとともに注文未確定のバッジを表示させるようにした。
次いで新規登録時には最新の注文がないので最新の注文に対してnil?を加え、新規注文作成画面においては注文自体は存在するがidがないのでid.nil?で判別するようにヘッダのリンク先分岐部分を書き換えた。
問題解決により実現したこと
確認画面でもう一度買い物を続けたりお届け先情報の編集
注文未確定の場合にログアウトさせないこと

解決方法の部分が長くなりましたがレイアウト的にあれなら要約だけしてもらって大丈夫です。
やったプロセスを全て書いたのでこの部分は発表時に原稿として持っておくか質疑応答に備えておくつもりくらいでいます。

**Comment by way-key** [comment]
2.の修正

- 存在していた問題点
管理者ページでログイン後、顧客側でもログインできてしまっていた。(その逆も可能)
それにより、ヘッダーの表示が意図しない状態となった。

- 解決方法
コントローラに片方でログインしていた場合、もう片方のページに遷移したらトップページにリダイレクトするようbefore_action!を記述した。

- 解決により実現したこと
両方ログインできる状態が解消された。
